server:
  port: 8081

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        #     for manual configuration of route
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/auth/**

        - id: portfolio-service
          uri: lb://PORTFOLIO-SERVICE
          predicates:
            - Path=/iamneo/**
          filters:
            - RewritePath=/iamneo/(?<segment>.*), /portfolio-service/${segment}

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payment/buy


eureka:
  instance:
    prefer-ip-address:  true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: https://8080-ccbbabdaccdcbbeefcddfeabfccfa.project.examly.io/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"