server:
  port: 8081

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        #     for manual configuration of route
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/auth/**


eureka:
  instance:
    prefer-ip-address:  true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: https://8080-ccbbabdaccdcbbeefcddfeabfccfa.project.examly.io/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"